# Generated by Django 6.0.1 on 2026-01-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="task_images/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
