# Generated by Django 6.0.1 on 2026-04-21 16:49

import autoslug.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="name"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("author", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("author", "slug")},
        ),
    ]
