# Generated by Django 6.0.1 on 2026-04-19 01:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="title", unique=True
            ),
        ),
    ]
