# Generated by Django 6.0.1 on 2026-04-21 16:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_category_slug_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="title"
            ),
        ),
    ]
