# Generated by Django 6.0.1 on 2026-04-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
